# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 11:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='cover_image',
            field=models.ImageField(default=datetime.datetime(2016, 2, 18, 11, 14, 50, 378503, tzinfo=utc), upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='image_1',
            field=models.ImageField(default=datetime.datetime(2016, 2, 18, 11, 14, 59, 706005, tzinfo=utc), upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='image_2',
            field=models.ImageField(default=datetime.datetime(2016, 2, 18, 11, 15, 3, 874122, tzinfo=utc), upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='image_3',
            field=models.ImageField(default=datetime.datetime(2016, 2, 18, 11, 15, 6, 689768, tzinfo=utc), upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='tagline',
            field=models.CharField(default=datetime.datetime(2016, 2, 18, 11, 15, 10, 474005, tzinfo=utc), max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
