# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_website',
            field=models.CharField(default=b'http://myclub.com', max_length=50),
        ),
        migrations.AddField(
            model_name='club',
            name='contact_email',
            field=models.CharField(default=b'dweiss@haverford.edu', max_length=20),
        ),
        migrations.AddField(
            model_name='club',
            name='contact_person',
            field=models.CharField(default=b'Dan Weiss', max_length=20),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(default=b'Your Club Name Here', max_length=20),
        ),
        migrations.AlterField(
            model_name='club',
            name='tagline',
            field=models.CharField(default=b'Something clever.', max_length=40),
        ),
    ]
